Metadata-Version: 2.1
Name: rhinoinside
Version: 0.1.1
Summary: Embed Rhino in CPython
Home-page: https://github.com/mcneel/rhino.inside/tree/master/CPython
Author: Robert McNeel & Associates
Author-email: steve@mcneel.com
License: UNKNOWN
Platform: UNKNOWN
Classifier: Development Status :: 3 - Alpha
Classifier: Intended Audience :: Developers
Classifier: License :: OSI Approved :: MIT License
Classifier: Operating System :: Microsoft :: Windows
Classifier: Programming Language :: Python
Description-Content-Type: text/markdown
Requires-Dist: pythonnet

# rhinoinside python package
Embed Rhino in CPython

`pip install --user rhinoinside`

## Requirements:
- Rhino 7
- Windows
- 64 bit version of CPython (2.7+ or 3.3+ should work)

## How to use
```
import rhinoinside
import System
import Rhino

# for now, you need to explicitly use floating point
# numbers in Point3d constructor
pts = System.Collections.List[Rhino.Geometry.Point3d]()
pts.Add(Rhino.Geometry.Point3d(0.0,0.0,0.0))
pts.Add(Rhino.Geometry.Point3d(1.0,0.0,0.0))
pts.Add(RHino.Geometry.Point3d(1.5,2.0,0.0))

crv = Rhino.Geometry.Curve.CreateInterpolatedCurve(pts,3)
print (crv.GetLength())
```


